//LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//CLEAR
export const CLEAR_REQUEST = "CLEAR_REQUEST";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_FAILURE = "CLEAR_FAILURE";